const { contextBridge, ipcRenderer } = require('electron')

const CHANNELS = [
  'dashboard:stats', 'dashboard:salesTrend', 'dashboard:salesByPayment', 'dashboard:lowStock',
  'dashboard:weekComparison', 'dashboard:heatmap', 'dashboard:monthlyProfit',
  'products:list', 'products:get', 'products:create', 'products:update', 'products:delete', 'products:search',
  'sales:list', 'sales:get', 'sales:create', 'sales:void',
  'clients:list', 'clients:get', 'clients:create', 'clients:update', 'clients:delete',
  'clients:history', 'clients:addPayment',
  'clients:importCSV', 'clients:birthdays', 'clients:birthdayMonth', 'clients:ranking',
  'shell:openExternal',
  'accounts:list', 'accounts:movements',
  'suppliers:list', 'suppliers:get', 'suppliers:create', 'suppliers:update', 'suppliers:delete',
  'suppliers:history', 'suppliers:addPayment',
  'purchases:list', 'purchases:get', 'purchases:create',
  'cashbox:current', 'cashbox:open', 'cashbox:close', 'cashbox:history', 'cashbox:summary',
  'cashbox:movements', 'cashbox:addMovement', 'cashbox:report',
  'sucursales:list', 'sucursales:create', 'sucursales:update', 'sucursales:delete',
  'sucursales:transfer', 'sucursales:transfers', 'sucursales:salesBySucursal',
  'expenses:list', 'expenses:create', 'expenses:delete',
  'reports:salesByPeriod', 'reports:topProducts', 'reports:profitability',
  'reports:salesByCategory', 'reports:exportCSV',
  'reports:salesByProduct', 'reports:todaySalesDetail',
  'invoices:list', 'invoices:create',
  'audit:list',
  'orders:list', 'orders:get', 'orders:create', 'orders:update', 'orders:delete',
  'email:sendReport', 'email:test', 'email:sendSaleInvoice', 'email:sendStockReport',
  'settings:get', 'settings:set', 'settings:getAll',
  'googledrive:auth', 'googledrive:backup', 'googledrive:status', 'googledrive:disconnect', 'googledrive:clearTokens',
  'afip:generarCAE', 'afip:consultarUltimoComprobante', 'afip:status', 'afip:testConexion',
  'inventory:start', 'inventory:getCurrent', 'inventory:scan', 'inventory:increment',
  'inventory:updateItem', 'inventory:close', 'inventory:exportPDF', 'inventory:emailReport',
  'inventory:history', 'inventory:getReport',
  'email:sendTicket', 'email:saveTicketPDF',
  'shell:openPath',
  'tn:connect', 'tn:status', 'tn:disconnect',
  'tn:syncProducts', 'tn:syncStock', 'tn:syncAll',
  'tn:getOrders', 'tn:importOrder',
  'tn:syncProduct', 'tn:syncCustomers', 'tn:importCustomer',
  'tn:salesToday',
  'auth:login', 'auth:logout', 'auth:session', 'auth:lastUser',
  'auth:users:list', 'auth:users:create', 'auth:users:update',
  'auth:users:delete', 'auth:users:changePassword',
  'reports:commissions',
  'license:status', 'license:activate',
  'clients:points:history', 'clients:points:adjust',
  'products:setTnSync', 'products:bulkAction', 'products:exportCSV', 'products:csvTemplate',
  'products:importCSV', 'products:getVariants', 'products:createVariant', 'products:searchByBarcode',
  'email:sendPointsSummary',
  'exchanges:create', 'exchanges:list',
  'returns:create', 'returns:list',
  'senas:list', 'senas:pending', 'senas:create', 'senas:update',
  'senas:withdraw', 'senas:cancel', 'senas:checkExpired',
  'sellers:list', 'sellers:add', 'sellers:update', 'sellers:delete',
  'mp:getConfig', 'mp:saveConfig', 'mp:testConnection', 'mp:checkPayment',
  'mp:createPos', 'mp:getPos', 'mp:createOrder', 'mp:pollOrder', 'mp:cancelOrder',
  'stockentry:list', 'stockentry:get', 'stockentry:create',
  'egreso:list', 'egreso:get', 'egreso:create', 'egreso:updateStatus', 'egreso:pdf',
  'updater:checkManual', 'updater:openReleasePage', 'updater:downloadAndInstall', 'updater:getCurrentVersion',
  'remito:list', 'remito:get', 'remito:create', 'remito:updateStatus', 'remito:delete',
  'fixedcosts:list', 'fixedcosts:create', 'fixedcosts:update', 'fixedcosts:delete', 'fixedcosts:total',
  'weeklySummary:send',
  'waitlist:list', 'waitlist:pending', 'waitlist:add', 'waitlist:notify', 'waitlist:complete', 'waitlist:delete',
  'reports:rankingProductos', 'reports:rankingPrev', 'reports:colorAnalysis',
  'reports:clientDebt', 'reports:priceHistoryReport', 'reports:priceHistoryProduct',
  'dashboard:monthComparison', 'dashboard:categoryComparison',
  'backup:create', 'backup:restore',
  'products:priceHistory',
  'fiscal:stats', 'fiscal:ivaVentas', 'fiscal:ivaCompras', 'fiscal:posicion', 'fiscal:monotributo12m',
  'afip:syncComprobantes',
  'app:changelog', 'app:markChangelogSeen',
  'intelligence:recommendations', 'intelligence:stockBreaks',
  'voucher:list', 'voucher:create', 'voucher:validate', 'voucher:use', 'voucher:delete',
  'consignment:products:list', 'consignment:products:set', 'consignment:sales:list',
  'consignment:pending', 'consignment:liquidate', 'consignment:liquidations:list',
  'consignment:liquidation:get', 'consignment:sales:record',
  'ivabook:ventas', 'ivabook:compras', 'ivabook:exportCSV', 'ivabook:exportSIAP', 'ivabook:emailContador',
  'monthlySummary:send',
]

contextBridge.exposeInMainWorld('electron', {
  invoke: (channel, data) => {
    if (!CHANNELS.includes(channel)) throw new Error(`Canal no permitido: ${channel}`)
    return ipcRenderer.invoke(channel, data)
  },
  on: (channel, cb) => {
    const sub = (_, v) => cb(v)
    ipcRenderer.on(channel, sub)
    return () => ipcRenderer.removeListener(channel, sub)
  },
  window: {
    minimize: () => ipcRenderer.send('window:minimize'),
    maximize: () => ipcRenderer.send('window:maximize'),
    close: () => ipcRenderer.send('window:close'),
  },
})
