const inv = (ch, data) => window.electron.invoke(ch, data)

export const api = {
  dashboard: {
    stats:              () => inv('dashboard:stats'),
    salesTrend:         () => inv('dashboard:salesTrend'),
    salesByPayment:     () => inv('dashboard:salesByPayment'),
    localSalesPeriod:   (p) => inv('dashboard:localSalesPeriod', p),
    lowStock:           () => inv('dashboard:lowStock'),
    weekComparison:     () => inv('dashboard:weekComparison'),
    heatmap:            () => inv('dashboard:heatmap'),
    monthlyProfit:      () => inv('dashboard:monthlyProfit'),
    monthComparison:    () => inv('dashboard:monthComparison'),
    categoryComparison: () => inv('dashboard:categoryComparison'),
  },
  products: {
    list:            (p)       => inv('products:list', p),
    get:             (id)      => inv('products:get', id),
    create:          (d)       => inv('products:create', d),
    update:          (id, d)   => inv('products:update', { id, ...d }),
    delete:          (id)      => inv('products:delete', id),
    search:          (q)       => inv('products:search', { q }),
    setTnSync:       (id, val) => inv('products:setTnSync', { id, value: val }),
    searchByBarcode: (code)    => inv('products:searchByBarcode', code),
    bulkAction:      (d)       => inv('products:bulkAction', d),
    exportCSV:       ()        => inv('products:exportCSV'),
    csvTemplate:     ()        => inv('products:csvTemplate'),
    importCSV:       ()        => inv('products:importCSV'),
    getVariants:     (id)      => inv('products:getVariants', id),
    createVariant:   (d)       => inv('products:createVariant', d),
    priceHistory:    (id)      => inv('products:priceHistory', id),
  },
  sales: {
    list: (p) => inv('sales:list', p),
    get: (id) => inv('sales:get', id),
    create: (d) => inv('sales:create', d),
    void: (id, reason) => inv('sales:void', { id, reason: reason || '' }),
  },
  clients: {
    list: (p) => inv('clients:list', p),
    get: (id) => inv('clients:get', id),
    create: (d) => inv('clients:create', d),
    update: (id, d) => inv('clients:update', { id, ...d }),
    delete: (id) => inv('clients:delete', id),
    history: (id) => inv('clients:history', id),
    addPayment: (d) => inv('clients:addPayment', d),
    importCSV:     ()  => inv('clients:importCSV'),
    birthdays:     ()  => inv('clients:birthdays'),
    birthdayMonth: ()  => inv('clients:birthdayMonth'),
    ranking:       ()  => inv('clients:ranking'),
    points: {
      history: (id)   => inv('clients:points:history', id),
      adjust:  (d)    => inv('clients:points:adjust', d),
    },
  },
  accounts: {
    list: () => inv('accounts:list'),
    movements: (id) => inv('accounts:movements', id),
  },
  suppliers: {
    list: (p) => inv('suppliers:list', p),
    get: (id) => inv('suppliers:get', id),
    create: (d) => inv('suppliers:create', d),
    update: (id, d) => inv('suppliers:update', { id, ...d }),
    delete: (id) => inv('suppliers:delete', id),
    history: (id) => inv('suppliers:history', id),
    addPayment: (d) => inv('suppliers:addPayment', d),
  },
  supplierOrders: {
    list:           (p)  => inv('supplierorders:list', p),
    get:            (id) => inv('supplierorders:get', id),
    create:         (d)  => inv('supplierorders:create', d),
    update:         (d)  => inv('supplierorders:update', d),
    delete:         (id) => inv('supplierorders:delete', id),
    lowStock:       ()   => inv('supplierorders:lowStock'),
    convertToEntry: (id) => inv('supplierorders:convertToEntry', id),
  },
  purchases: {
    list: (p) => inv('purchases:list', p),
    get: (id) => inv('purchases:get', id),
    create: (d) => inv('purchases:create', d),
  },
  cashbox: {
    current:      ()   => inv('cashbox:current'),
    currentAll:   ()   => inv('cashbox:currentAll'),
    todaySummary: ()   => inv('cashbox:todaySummary'),
    open:         (d)  => inv('cashbox:open', d),
    close:        (d)  => inv('cashbox:close', d),
    history:      (p)  => inv('cashbox:history', p),
    summary:      (id) => inv('cashbox:summary', id),
    movements:    (id) => inv('cashbox:movements', id),
    addMovement:  (d)  => inv('cashbox:addMovement', d),
    report:       (id) => inv('cashbox:report', id),
  },
  sucursales: {
    list: () => inv('sucursales:list'),
    create: (d) => inv('sucursales:create', d),
    update: (id, d) => inv('sucursales:update', { id, ...d }),
    delete: (id) => inv('sucursales:delete', id),
    transfer: (d) => inv('sucursales:transfer', d),
    transfers: () => inv('sucursales:transfers'),
    salesBySucursal: (p) => inv('sucursales:salesBySucursal', p),
  },
  expenses: {
    list: (p) => inv('expenses:list', p),
    create: (d) => inv('expenses:create', d),
    delete: (id) => inv('expenses:delete', id),
  },
  reports: {
    salesByPeriod:       (p) => inv('reports:salesByPeriod', p),
    topProducts:         (p) => inv('reports:topProducts', p),
    profitability:       (p) => inv('reports:profitability', p),
    salesByCategory:     (p) => inv('reports:salesByCategory', p),
    exportCSV:           (p) => inv('reports:exportCSV', p),
    salesByProduct:      (p) => inv('reports:salesByProduct', p),
    todaySalesDetail:    ()  => inv('reports:todaySalesDetail'),
    commissions:         (p) => inv('reports:commissions', p),
    rankingProductos:    (p) => inv('reports:rankingProductos', p),
    rankingPrev:         (p) => inv('reports:rankingPrev', p),
    colorAnalysis:       (p) => inv('reports:colorAnalysis', p),
    clientDebt:          ()  => inv('reports:clientDebt'),
    priceHistoryReport:  (p) => inv('reports:priceHistoryReport', p),
    priceHistoryProduct: (p) => inv('reports:priceHistoryProduct', p),
    sinMovimiento:       (p) => inv('reports:sinMovimiento', p),
    liquidarProductos:   (p) => inv('reports:liquidarProductos', p),
    vendedoras:          (p) => inv('reports:vendedoras', p),
    rentabilidadCategorias: (p) => inv('reports:rentabilidadCategorias', p),
  },
  orders: {
    list: (p) => inv('orders:list', p),
    get: (id) => inv('orders:get', id),
    create: (d) => inv('orders:create', d),
    update: (id, d) => inv('orders:update', { id, ...d }),
    delete: (id) => inv('orders:delete', id),
  },
  email: {
    sendReport: (cashboxId) => inv('email:sendReport', cashboxId),
    test: () => inv('email:test'),
    sendSaleInvoice: (d) => inv('email:sendSaleInvoice', d),
    sendTicket: (d) => inv('email:sendTicket', d),
    saveTicketPDF: (saleId) => inv('email:saveTicketPDF', saleId),
    sendPointsSummary: (d) => inv('email:sendPointsSummary', d),
    sendStockReport: () => inv('email:sendStockReport'),
  },
  invoices: {
    list: (p) => inv('invoices:list', p),
    create: (d) => inv('invoices:create', d),
  },
  audit: {
    list: (p) => inv('audit:list', p),
  },
  settings: {
    get:    (key)        => inv('settings:get', key),
    set:    (key, value) => inv('settings:set', { key, value }),
    getAll: ()           => inv('settings:getAll'),
  },
  mp: {
    getConfig:     ()        => inv('mp:getConfig'),
    saveConfig:    (d)       => inv('mp:saveConfig', d),
    testConnection:(d)       => inv('mp:testConnection', d),
    checkPayment:  (d)       => inv('mp:checkPayment', d),
    createPos:     (d)       => inv('mp:createPos', d),
    getPos:        ()        => inv('mp:getPos'),
    createOrder:   (d)       => inv('mp:createOrder', d),
    pollOrder:     (d)       => inv('mp:pollOrder', d),
    cancelOrder:   (d)       => inv('mp:cancelOrder', d),
  },
  sellers: {
    list:   ()           => inv('sellers:list'),
    add:    (d)          => inv('sellers:add', d),
    update: (id, d)      => inv('sellers:update', { id, ...d }),
    delete: (id)         => inv('sellers:delete', id),
  },
  googledrive: {
    auth:       () => inv('googledrive:auth'),
    backup:     () => inv('googledrive:backup'),
    status:     () => inv('googledrive:status'),
    disconnect:  () => inv('googledrive:disconnect'),
    clearTokens: () => inv('googledrive:clearTokens'),
  },
  waitlist: {
    list:     (p) => inv('waitlist:list', p),
    pending:  ()  => inv('waitlist:pending'),
    add:      (d) => inv('waitlist:add', d),
    notify:   (id) => inv('waitlist:notify', id),
    complete: (id) => inv('waitlist:complete', id),
    delete:   (id) => inv('waitlist:delete', id),
  },
  afip: {
    status:                    ()  => inv('afip:status'),
    testConexion:              ()  => inv('afip:testConexion'),
    consultarUltimoComprobante:(p) => inv('afip:consultarUltimoComprobante', p),
    generarCAE:                (d) => inv('afip:generarCAE', d),
  },
  shell: {
    openExternal: (url) => inv('shell:openExternal', url),
    openPath: (p) => inv('shell:openPath', p),
  },
  inventory: {
    start:       (notes) => inv('inventory:start', notes),
    getCurrent:  ()      => inv('inventory:getCurrent'),
    scan:        (d)     => inv('inventory:scan', d),
    increment:   (d)     => inv('inventory:increment', d),
    updateItem:  (d)     => inv('inventory:updateItem', d),
    close:       (d)     => inv('inventory:close', d),
    exportPDF:   (id)    => inv('inventory:exportPDF', id),
    emailReport: (id)    => inv('inventory:emailReport', id),
    history:     (p)     => inv('inventory:history', p),
    getReport:   (id)    => inv('inventory:getReport', id),
  },
  auth: {
    login:              (d)      => inv('auth:login', d),
    logout:             ()       => inv('auth:logout'),
    session:            ()       => inv('auth:session'),
    lastUser:           (u)      => inv('auth:lastUser', u),
    users: {
      list:             ()       => inv('auth:users:list'),
      create:           (d)      => inv('auth:users:create', d),
      update:           (id, d)  => inv('auth:users:update', { id, ...d }),
      delete:           (id)     => inv('auth:users:delete', id),
      changePassword:   (id, pw) => inv('auth:users:changePassword', { id, password: pw }),
    },
  },
  license: {
    status:   ()     => inv('license:status'),
    activate: (code) => inv('license:activate', code),
  },
  exchanges: {
    create: (d) => inv('exchanges:create', d),
    list:   (p) => inv('exchanges:list', p),
  },
  returns: {
    create: (d) => inv('returns:create', d),
    list:   (p) => inv('returns:list', p),
  },
  stockentry: {
    list:   (p) => inv('stockentry:list', p),
    get:    (id) => inv('stockentry:get', id),
    create: (d)  => inv('stockentry:create', d),
  },
  updater: {
    checkManual:          () =>      inv('updater:checkManual'),
    openReleasePage:      (url) =>   inv('updater:openReleasePage', url),
    downloadAndInstall:   () =>      inv('updater:downloadAndInstall'),
    getCurrentVersion:    () =>      inv('updater:getCurrentVersion'),
  },
  egreso: {
    list:         (p)  => inv('egreso:list', p),
    get:          (id) => inv('egreso:get', id),
    create:       (d)  => inv('egreso:create', d),
    updateStatus: (d)  => inv('egreso:updateStatus', d),
    pdf:          (id) => inv('egreso:pdf', id),
  },
  senas: {
    list:         (p) => inv('senas:list', p),
    pending:      ()  => inv('senas:pending'),
    create:       (d) => inv('senas:create', d),
    update:       (d) => inv('senas:update', d),
    withdraw:     (d) => inv('senas:withdraw', d),
    cancel:       (d) => inv('senas:cancel', d),
    checkExpired: ()  => inv('senas:checkExpired'),
  },
  remito: {
    list:         (p) => inv('remito:list', p),
    get:          (id) => inv('remito:get', id),
    create:       (d) => inv('remito:create', d),
    updateStatus: (d) => inv('remito:updateStatus', d),
    delete:       (id) => inv('remito:delete', id),
  },
  fixedcosts: {
    list:   ()    => inv('fixedcosts:list'),
    create: (d)   => inv('fixedcosts:create', d),
    update: (d)   => inv('fixedcosts:update', d),
    delete: (id)  => inv('fixedcosts:delete', id),
    total:  ()    => inv('fixedcosts:total'),
  },
  weeklySummary: {
    send: () => inv('weeklySummary:send'),
  },
  backup: {
    create:  (password) => inv('backup:create',  { password }),
    restore: (password) => inv('backup:restore', { password }),
  },
  fiscal: {
    stats:          ()  => inv('fiscal:stats'),
    ivaVentas:      (p) => inv('fiscal:ivaVentas',      p),
    ivaCompras:     (p) => inv('fiscal:ivaCompras',     p),
    posicion:       ()  => inv('fiscal:posicion'),
    monotributo12m: ()  => inv('fiscal:monotributo12m'),
    syncComprobantes: (p) => inv('afip:syncComprobantes', p),
  },
  app: {
    changelog:         () => inv('app:changelog'),
    markChangelogSeen: () => inv('app:markChangelogSeen'),
  },
  intelligence: {
    recommendations: () => inv('intelligence:recommendations'),
    stockBreaks:     () => inv('intelligence:stockBreaks'),
    stockSpecular:   () => inv('intelligence:stockSpecular'),
  },
  cashflow: {
    projection: () => inv('cashflow:projection'),
  },
  breakeven: {
    data: () => inv('breakeven:data'),
  },
  supplieranalytics: {
    margins: (p) => inv('supplieranalytics:margins', p),
  },
  onboarding: {
    status:  () => inv('onboarding:status'),
    dismiss: () => inv('onboarding:dismiss'),
    reset:   () => inv('onboarding:reset'),
  },
  health: {
    score: () => inv('health:score'),
  },
  vouchers: {
    list:     (p)    => inv('voucher:list', p),
    create:   (d)    => inv('voucher:create', d),
    validate: (code) => inv('voucher:validate', { code }),
    use:      (d)    => inv('voucher:use', d),
    delete:   (id)   => inv('voucher:delete', id),
  },
  consignment: {
    products: {
      list: ()  => inv('consignment:products:list'),
      set:  (d) => inv('consignment:products:set', d),
    },
    sales: {
      list:   (p) => inv('consignment:sales:list', p),
      record: (d) => inv('consignment:sales:record', d),
    },
    pending:      ()    => inv('consignment:pending'),
    liquidate:    (d)   => inv('consignment:liquidate', d),
    liquidations: {
      list: ()   => inv('consignment:liquidations:list'),
      get:  (id) => inv('consignment:liquidation:get', id),
    },
  },
  ivabook: {
    ventas:        (p) => inv('ivabook:ventas', p),
    compras:       (p) => inv('ivabook:compras', p),
    exportCSV:     (p) => inv('ivabook:exportCSV', p),
    exportSIAP:    (p) => inv('ivabook:exportSIAP', p),
    emailContador: (p) => inv('ivabook:emailContador', p),
  },
  tn: {
    connect:        ()    => inv('tn:connect'),
    status:         ()    => inv('tn:status'),
    disconnect:     ()    => inv('tn:disconnect'),
    syncProducts:   ()    => inv('tn:syncProducts'),
    syncProduct:    (id)  => inv('tn:syncProduct', id),
    syncStock:      ()    => inv('tn:syncStock'),
    syncAll:        ()    => inv('tn:syncAll'),
    getOrders:      (p)   => inv('tn:getOrders', p),
    importOrder:    (id)  => inv('tn:importOrder', id),
    syncCustomers:  ()    => inv('tn:syncCustomers'),
    importCustomer: (id)  => inv('tn:importCustomer', id),
    salesToday:     ()    => inv('tn:salesToday'),
    salesPeriod:    (p)   => inv('tn:salesPeriod', p),
  },
}
